databases:
  - name: qrmenu-db
    plan: free
    databaseName: qrmenu
    user: qrmenu

services:
  - type: web
    name: qrmenu-backend
    plan: free
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn qrmenu_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qrmenu-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: STRIPE_API_SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.6"
